# Generated by Django 4.2.5 on 2023-12-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan', models.CharField(max_length=100)),
                ('burger', models.CharField(max_length=100)),
                ('minuman', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=100)),
                ('service', models.TextField()),
                ('booking', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('testimonial', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.menu')),
            ],
        ),
    ]
