# Generated by Django 4.2.5 on 2023-12-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
